"""Add naming conventions and initial models

Revision ID: 46213a17565f
Revises: 
Create Date: 2025-04-21 11:38:05.388323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46213a17565f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_event_id', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('depth_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('magnitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disaster_id', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('disaster_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_disaster_report_disaster_id'), ['disaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_report_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_report_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_report_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_report_verified'), ['verified'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_disaster_report_disaster_id_disaster'), 'disaster', ['disaster_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('disaster_report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_disaster_report_disaster_id_disaster'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_disaster_report_verified'))
        batch_op.drop_index(batch_op.f('ix_disaster_report_user_id'))
        batch_op.drop_index(batch_op.f('ix_disaster_report_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_disaster_report_source'))
        batch_op.drop_index(batch_op.f('ix_disaster_report_disaster_id'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('disaster_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('disaster_id')
        batch_op.drop_column('magnitude')
        batch_op.drop_column('depth_km')
        batch_op.drop_column('source')
        batch_op.drop_column('source_event_id')

    # ### end Alembic commands ###
