"""Add status field to DisasterReport

Revision ID: 7f71deb93c20
Revises: 46213a17565f
Create Date: 2025-05-07 14:32:59.564305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f71deb93c20'
down_revision = '46213a17565f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='pending'))
        batch_op.create_index(batch_op.f('ix_disaster_report_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_report_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
